baseURL = "https://kb.jemoka.com/"
languageCode = "en-us"
title = "knowledgebase"
refLinksErrorLevel = "WARNING"

[outputs]
home = [ "html", "rss", "json" ]

[markup.highlight]
codeFences = true
noClasses = true
noHl = false
style = "monokailight"
tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Houjun Liu"
description = "eat a chicken efficiently"
