baseURL: 'http://example.org/'
languageCode: en-us
title: knowledgebase
refLinksErrorLevel: WARNING


markup:
  highlight:
    codeFences: true
    noClasses: true
    noHl: false
    style: monokailight
    tabWidth: 4

params:
  author: Houjun Liu
  description: eat a chicken efficiently

markup.goldmark.renderer:
  unsafe: true

